# Generated by Django 4.2.6 on 2023-12-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentooborot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='documents',
            name='doc_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='trud',
            name='order_status',
            field=models.TextField(verbose_name='Статус заявки'),
        ),
    ]
